language: go
sudo: required
services:
  - docker
go:
  - 1.6
before_install:
  - openssl aes-256-cbc -K $encrypted_790acdb9ad25_key -iv $encrypted_790acdb9ad25_iv
    -in catalogue_deploy_rsa.enc -out catalogue_deploy_rsa -d
  - go get -u github.com/FiloSottile/gvt
  - gvt restore
  - go get -u github.com/mattn/goveralls

install: true

env:
  - GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=catalogue;

script:
  - set -e
  - ./scripts/build.sh;
  - ./test/test.sh unit.py
 # - ./test/test.sh component.py
  - ./test/test.sh container.py --tag $TAG

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
  - ./scripts/push.sh
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
addons:
  ssh_known_hosts: $BASTION
deploy:
  provider: script
  skip_cleanup: true
  # The deploy.sh file actually points to the deploy file on the bastion. Not one in the repo.
  script: ssh -o StrictHostKeyChecking=no $BASTION_USER@$BASTION ./deploy.sh ${REPO} $COMMIT
  on:
    branch: master
